project:
  type: website
  output-dir: _site

website:
  title: "AI Readiness Primer"
  description: "A primer resource for AI readiness in the community"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
